name: Pull Request
on:
  pull_request:
    branches:
      - main
      - beta
jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: yarn

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint

      - name: Check
        run: yarn check
